spring.profiles.active: test

---
spring:
 profiles: development
db:
  username: admin
  password: 12345

---
server:
  port: 9999
spring:
 profiles: test
 view:
  prefix: /WEB-INF/jsp/
  suffix: .jsp
db:
  username: admin_test
  password: 12345_test
